[package]
name = "pwmp-server"
version = "2.0.0"
edition = "2021"
authors = ["Fábián Varga <23280129+br0kenpixel@users.noreply.github.com>"]
description = "The PixelWeather Messaging Protocol server."
rust-version = "1.85"
homepage = "https://github.com/PixelWeatherProject"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/PixelWeatherProject/pwmp-server"

[profile.release]
strip = true

[dependencies]
pwmp-client = { git = "ssh://git@github.com/PixelWeatherProject/pwmp-client.git", tag = "v2.0.1" }
sqlx = { version = "0.8.3", default-features = false, features = [
    "postgres",
    "runtime-tokio",
    "migrate",
    "macros",
    "rust_decimal",
    "tls-rustls",
] }
tokio = { version = "1.43.0", default-features = false, features = [
    "rt-multi-thread",
] }
clap = { version = "4.5.26", features = ["derive"] }
confy = { version = "0.6.1", default-features = false, features = [
    "yaml_conf",
] }
homedir = { version = "0.3.4", default-features = false }
log = { version = "0.4.22", features = ["std"] }
serde = { version = "1.0.217", features = ["derive"] }
simple_logger = { version = "5.0.0", default-features = false, features = [
    "colors",
    "colored",
    "stderr",
    "timestamps",
] }
thiserror = "2.0.11"
time = { version = "0.3.37", default-features = false, features = ["macros"] }
rust_decimal = { version = "1.36.0", features = ["db-diesel-postgres"] }
users = { version = "0.11.0", default-features = false }
serde_with = "3.12.0"
color-print = "0.3.7"
