[package]
name = "pwmp-server"
version = "2.1.2"
edition = "2024"
authors = ["Fábián Varga <23280129+br0kenpixel@users.noreply.github.com>"]
description = "The PixelWeather Messaging Protocol server."
rust-version = "1.85"
homepage = "https://github.com/PixelWeatherProject"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/PixelWeatherProject/pwmp-server"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true

[dependencies]
pwmp-client = { git = "https://github.com/PixelWeatherProject/pwmp-client.git", tag = "v2.1.6" }
sqlx = { version = "0.8.3", default-features = false, features = [
    "postgres",
    "runtime-tokio",
    "migrate",
    "macros",
    "tls-rustls",
] }
tokio = { version = "1.43.0", default-features = false, features = [
    "rt-multi-thread",
] }
clap = { version = "4.5.28", features = ["derive"] }
confy = { version = "0.6.1", default-features = false, features = [
    "yaml_conf",
] }
homedir = { version = "0.3.4", default-features = false }
log = { version = "0.4.27", features = ["std"] }
serde = { version = "1.0.219", features = ["derive"] }
simple_logger = { version = "5.0.0", default-features = false, features = [
    "colors",
    "colored",
    "stderr",
    "timestamps",
] }
thiserror = "2.0.12"
time = { version = "0.3.37", default-features = false, features = ["macros"] }
users = { version = "0.11.0", default-features = false }
serde_with = "3.12.0"
color-print = "0.3.7"
arrayref = "0.3.9"
libc = { version = "0.2.171", default-features = false }
semaphore = "0.4.0"
circular-queue = "0.2.7"
signal-hook = "0.3.17"
