[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main"
# Fix for https://github.com/rustls/rustls/issues/1967
pre-build = [
    "apt-get update && apt-get remove --assume-yes gcc-9 && apt-get --assume-yes install gcc-10 clang",
]

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"
