name: pwmp-server

services:
    pwmp-server:
      container_name: pwmp-server
      stdin_open: true
      tty: true

      build:
        context: .
        dockerfile: Dockerfile
      
      restart: unless-stopped

      volumes:
          - ~/.pwmp-server:/config:ro
      
      ports:
          - 55300:55300
    
    postgres:
      container_name: pwmp-server
      
      image: postgres:17.4-alpine3.21
      restart: unless-stopped
      
      environment:
        POSTGRES_PASSWORD: 'root'
        POSTGRES_USER: 'root'
        POSTGRES_DB: 'root_db'
        PGTZ: 'Europe/Bratislava'
        TZ: 'Europe/Bratislava'
      
      ports:
        - 5432:5432
      
      expose:
        - '5432'
      
      volumes:
        - ./postgres-data:/var/lib/postgresql/data